### ISSUE TITLE
您好，加了此仓库到聚合演示

### ISSUE THREAD

**Issue by nobodxbodon** [Tiphereth-A/Tiphereth-A.github.io#102]
基于 [此内容聚合设想](https://gitee.com/zhishi/collection-of-chinese-blogs/)，用gh pages搭了 [这个演示](http://nobodxbodon.github.io/)。博客同步、索引和网页内容生成等源码都 [在此](https://gitee.com/zhishi/collection-of-chinese-blogs/tree/master/%E5%8E%9F%E5%9E%8B)。
现在仅有最基本的浏览和搜索功能，打算尽量定期同步内容并补充功能，会 [在此报告](https://github.com/nobodxbodon/nobodxbodon.github.io/issues/1) 阶段进展。

刚加了您的仓库入内置仓库列表。之前加过另一位 [竞赛博主](https://github.com/Hukeqing/Hukeqing.github.io)。
欢迎任何建议意见！

**Comment by Tiphereth-A** [comment]
首先，欢迎您在遵守本博客版权声明的前提下转载本博客内容。根据本博客目前采用的 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) 协议，您在转载本博客内容时需要保留本博客的版权声明。

另外，目前跳转至站点原文的超链接有一些问题。

**Comment by nobodxbodon** [comment]
谢谢，版权声明和原文链接刚作 [如此](https://nobodxbodon.github.io/tifa-233.com/%E9%9A%8F%E7%AC%94%20-%20%E6%89%B9%E9%87%8F%E9%87%8D%E5%91%BD%E5%90%8D%20APK%20%E6%96%87%E4%BB%B6%E7%9A%84%20Python%20%E8%84%9A%E6%9C%AC.html) 修正。
